### ISSUE TITLE
SKR 2 Timeout

### ISSUE THREAD

**Issue by AfroPsycho** [rmpel/direct-serial-connection-raspi-3dprinter#1]
Hey,
I have followed the steps you made but when I try to connect it does not and after a while it times out 
I have check the wiring couple of times as well as changes made in the octopi/marlin (gnd -> gnd, tx -> pa10, rx -> pa9) no 5v connected between skr and rpi

Quick note raspberry and skr is both powered by the printers powersupply but there is a stepdown converter between rpi and psu can it be a trouble for the common gnd?

**Comment by AfroPsycho** [comment]
> Hey, I have followed the steps you made but when I try to connect it does not and after a while it times out I have check the wiring couple of times as well as changes made in the octopi/marlin (gnd -> gnd, tx -> pa10, rx -> pa9) no 5v connected between skr and rpi
> 
> Quick note raspberry and skr is both powered by the printers powersupply but there is a stepdown converter between rpi and psu can it be a trouble for the common gnd?

After a clean installation of octopi here is the error I get
![image](https://user-images.githubusercontent.com/42263654/159645630-645e9fce-e1e2-4694-b7c1-9b4086d38971.png)

**Comment by AfroPsycho** [comment]
Alright after a clean installation of octopi / octoprint (stable)

`Changing monitoring state from "Offline" to "Opening serial connection"
Connecting to port /dev/ttyAMA0, baudrate 250000
Changing monitoring state from "Opening serial connection" to "Connecting"
Connected to: Serial<id=0xaf2b7670, open=True>(port='/dev/ttyAMA0', baudrate=250000, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Send: N0 M110 N0*125
Recv: o\x00k
WARNThe received line contains at least one null byte character at position 1, this hints at some data corruption going on
No answer from the printer within the connection timeout, trying another hello
Send: N0 M110 N0*125
Recv: ok`

it did end up connecting but what does that mean
maybe because of unshielded cable?

**Comment by rmpel** [comment]
Log mentions "Data corruption" ... I can't remember if this is the same error I had, but I did at one time have problems connecting on my Ender 5 and I switched to a repurposed USB cable (just cut a piece from an old cable ;) ) and used that to create a new cable. In my case, it helped, no more errors.

You also mentioned "trouble for the common ground"; if there is no common ground, communication will not work, so considering your second reasonably well attempt; the common ground seems ok ;)
